version: "3"

services:
  db:
    env_file:
      - .db.turtle.env
    image: mariadb:10.6.4
    container_name: db.turtle
    networks:
      - turtle
    volumes:
      - turtle:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    command: --character-set-client-handshake=FALSE
  app:
    env_file:
      - .app.turtle.env
    image: lunacircle4/remember:1.1.0
    container_name: app.turtle
    networks:
      - turtle
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"

networks:
  turtle:
    name: turtle

volumes:
  turtle:
    name: turtle
